modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory

# The modid of the mod
modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
modId="forge" #mandatory

type="required" #mandatory

versionRange="${forge_version_range}" #mandatory

ordering="NONE"

side="BOTH"

mandatory = true

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    mandatory = true

[[dependencies.${mod_id}]]
    modId="fdlib"
    type="required"
    versionRange="${fdlib_version_range}"
    ordering="NONE"
    side="BOTH"
    mandatory = true


